config/routes.rb
ColetivoPontual::Application.routes.draw do
  root to: 'application#index'

  resources :devices do
    get 'tracked_index_stream', on: :collection
    get 'tracker', on: :member
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  def on_receive_position
    connection.execute "LISTEN tracker"
    connection.raw_connection.wait_for_notify do |event, pid, position|
      yield position
    end
  ensure
    connection.execute "UNLISTEN tracker"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Live

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  def tracked_index_stream
    response.headers['Content-Type'] = 'text/event-stream'
    devices = Device.all
    loop do
      devices.each do |device|
        device.on_receive_position do |position|
          response.stream.write(sse(position, {event: 'tracker'}))
        end
      end
    end
  rescue IOError
     # Client Disconnected
  ensure
    response.stream.close
  end

  def tracker
    Device.connection.execute "NOTIFY tracker, #{Device.connection.quote params[:position].to_json}"
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:title)
    end

    def sse(object, options = {})
      (options.map{|k,v| "#{k}: #{v}" } << "data: #{JSON.dump object}").join("\n") + "\n\n"
    end
end

app/views/application/index.haml
#tracked-stream

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Devices

%table.table
  - @devices.each do |device|
    %tr
      %td= button_to_function device.title, "new CP.BusDevice('#{device.id}', '#{device.title}')", class: 'btn'
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Novo', new_device_path, class: 'btn btn-large'

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  = @device.title


= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Coletivo Pontual", root_path, :class => 'brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Coletivo Pontual"
      %meta{:content => content_for?(:description) ? yield(:description) : "Coletivo Pontual", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBJ7fkG6h4PFzrThGM-SfPrg2x-NPRHQhA&sensor=true"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main